baseurl = "/"
languageCode = "en-us"
Title = "Non Player Blog"
theme = "pickles"
# Copyright notice. This is displayer in the footer.
copyright = "&copy; 2020 Eric Liao"

# Google Analytics API key.
googleAnalytics = "Your Google Analytics tracking id"

[params]
  paginate = 10
  # Social accounts. Link to these accounts are displayed in the header and
  # footer
  twitter = "rcliaodev"
  github = "rcliao"
  linkedin = "rcliao"
  # Short subtitle/tagline. This is displayed in the header.
  subtitle = "Software development blog"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 4

[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 80

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = false

  # Will lower case keywords in both queries and in the indexes.
  toLower = false

  [[related.indices]]
  name = "keywords"
  weight = 150
  [[related.indices]]
  name  = "author"
  toLower = true
  weight = 30
  [[related.indices]]
  name  = "tags"
  weight = 100
  [[related.indices]]
  name  = "date"
  weight = 10
  pattern = "2017"
